#!/bin/bash
# Install (or uninstall with -u) the H2SA plugins into the game.
# Works on mac (CrossOver bottle) and on Windows under Git Bash / MSYS2.
set -e
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        DEFAULT_GAME="/c/Program Files (x86)/Steam/steamapps/common/Hitman 2 Silent Assassin";;
    *)
        DEFAULT_GAME="$HOME/Library/Application Support/CrossOver/Bottles/Steam/drive_c/Program Files (x86)/Steam/steamapps/common/Hitman 2 Silent Assassin";;
esac
GAME="${H2SA_GAME_DIR:-$DEFAULT_GAME}"
HERE="$(cd "$(dirname "$0")" && pwd)"

# Files from before the snake_case rename / core merge (widescreen + profiler
# are now one h2sa_core.asi). Removed on install and uninstall; the old inis
# are only removed after their settings were migrated into h2sa_core.ini.
remove_legacy() {
    rm -f "$GAME/scripts/H2SAAsiLoader.log"
    rm -f "$GAME/scripts/H2SAWidescreen.asi"
    rm -f "$GAME/scripts/H2SAWidescreen.ini"
    rm -f "$GAME/scripts/H2SAWidescreen.log"
    rm -f "$GAME/scripts/H2SAProfiler.asi"
    rm -f "$GAME/scripts/H2SAProfiler.ini"
    rm -f "$GAME/scripts/H2SAProfiler.log"
    rm -f "$GAME/scripts/H2SAReducedX87.asi"
    rm -f "$GAME/scripts/H2SAReducedX87-diag.asi"
    rm -f "$GAME/scripts/H2SAReducedX87.log"
    rm -rf "$GAME/scripts/H2SAReducedX87"
    rm -f "$GAME/scripts/H2SADump.asi"
    rm -f "$GAME/scripts/H2SADump.log"
}

if [ "$1" = "-u" ]; then
    rm -f "$GAME/d3d8.dll"
    rm -f "$GAME/scripts/h2sa_asi_loader.log"
    rm -f "$GAME/scripts/h2sa_core.asi"
    rm -f "$GAME/scripts/h2sa_core.log"
    rm -f "$GAME/scripts/h2sa_reduced_x87.asi"
    rm -f "$GAME/scripts/h2sa_reduced_x87_diag.asi"
    rm -f "$GAME/scripts/h2sa_reduced_x87.log"
    rm -rf "$GAME/scripts/h2sa_reduced_x87"
    rm -f "$GAME/scripts/h2sa_dump.asi"
    rm -f "$GAME/scripts/h2sa_dump.log"
    remove_legacy
    # the plugin .ini is user config; left in place on purpose.
    # Hitman2.ini is not touched on uninstall; restore Hitman2.ini.bak by hand
    # if you want the original resolution back.
    echo "uninstalled (d3d8.dll + plugins removed; h2sa_core.ini and Hitman2.ini left as-is)"
    exit 0
fi

[ -f "$HERE/dist/d3d8.dll" ] || { echo "build first: (cd runtime && make)"; exit 1; }
[ -f "$HERE/dist/h2sa_core.asi" ] || { echo "build first: (cd runtime && make)"; exit 1; }
[ -d "$GAME" ] || { echo "game dir not found: $GAME (set H2SA_GAME_DIR)"; exit 1; }

mkdir -p "$GAME/scripts"

# Migrate a pre-rename install: the old per-plugin configs become the
# [Widescreen] / [Profiler] sections of the merged h2sa_core.ini.
OLD_WS_INI="$GAME/scripts/H2SAWidescreen.ini"
OLD_PF_INI="$GAME/scripts/H2SAProfiler.ini"
if [ ! -f "$GAME/scripts/h2sa_core.ini" ] &&
   { [ -f "$OLD_WS_INI" ] || [ -f "$OLD_PF_INI" ]; }; then
    {
        [ -f "$OLD_WS_INI" ] && { cat "$OLD_WS_INI"; echo; }
        [ -f "$OLD_PF_INI" ] && cat "$OLD_PF_INI"
    } > "$GAME/scripts/h2sa_core.ini"
    echo "migrated old H2SAWidescreen.ini/H2SAProfiler.ini settings -> scripts/h2sa_core.ini"
fi
remove_legacy

# ASI loader: d3d8.dll proxy in the game root (also carries the D3D8 hooks)
cp "$HERE/dist/d3d8.dll" "$GAME/d3d8.dll"

# Core plugin: widescreen + startup fix + mouse fixes + frame cap, plus the
# performance profiler overlay (top-right; [Profiler] section of the ini).
cp "$HERE/dist/h2sa_core.asi" "$GAME/scripts/"
if [ ! -f "$GAME/scripts/h2sa_core.ini" ]; then
    printf '[Widescreen]\nEnabled=1\nFullscreen=0\nBorderless=-1\nPreserveAspect=1\nFOVCorrect=1\nFOVFactor=1.0\nCursorFix=0\nFpsCap=60\nVSync=-1\nMouseClipFix=-1\nMouseMotionFix=-1\n\n[Profiler]\nEnabled=1\nScale=1.0\nShowCPU=1\nOffsetX=8\nOffsetY=8\n' \
        > "$GAME/scripts/h2sa_core.ini"
fi

# Reduced-precision x87 plugin: SSE2-translated RenderD3D.dll for CrossOver
# performance. The .asi loads any <module>.x87 blob from scripts/h2sa_reduced_x87/.
if [ -f "$HERE/dist/h2sa_reduced_x87.asi" ] && [ -f "$HERE/dist/RenderD3D.dll.x87" ]; then
    cp "$HERE/dist/h2sa_reduced_x87.asi" "$GAME/scripts/"
    # a stray diag build would also hook the game with helper-call counting
    # overhead; never leave one behind
    rm -f "$GAME/scripts/h2sa_reduced_x87_diag.asi"
    mkdir -p "$GAME/scripts/h2sa_reduced_x87"
    cp "$HERE/dist/RenderD3D.dll.x87" "$GAME/scripts/h2sa_reduced_x87/"
    msg="RenderD3D.dll.x87"
    # hitman2.exe.x87 (game-logic x87) is optional: generated by dumping the
    # packed exe once (see tools/undump.py / h2sa_dump.asi). Install if present.
    if [ -f "$HERE/dist/hitman2.exe.x87" ]; then
        cp "$HERE/dist/hitman2.exe.x87" "$GAME/scripts/h2sa_reduced_x87/"
        msg="$msg + hitman2.exe.x87"
    fi
    echo "x87 plugin: h2sa_reduced_x87.asi + $msg installed"
else
    echo "NOTE: x87 plugin not installed (build runtime + run tools/translate.py)"
fi

# Give widescreen out of the box: if Hitman2.ini still has the placeholder
# 800x600 (4:3), bump it to a 16:9 resolution. Set H2SA_RESOLUTION=WxH to
# override, or to your display resolution for borderless-fullscreen. The
# original is backed up to Hitman2.ini.bak.
RES="${H2SA_RESOLUTION:-1920x1080}"
INI="$GAME/Hitman2.ini"
if [ -f "$INI" ] && grep -qE '^Resolution[[:space:]]+800x600' "$INI"; then
    cp "$INI" "$INI.bak"
    # portable in-place edit (BSD/GNU sed differ on -i)
    sed "s/^Resolution[[:space:]].*/Resolution ${RES}/" "$INI" > "$INI.tmp" \
        && mv "$INI.tmp" "$INI"
    echo "Hitman2.ini: Resolution 800x600 -> ${RES} (backup: Hitman2.ini.bak)"
fi

# Wine/CrossOver: the game-directory d3d8.dll only loads with the DLL
# override d3d8=native,builtin. Add it to the bottle if we can find CrossOver.
if [ "$(uname -s)" != "Darwin" ]; then
    :  # real Windows: app-dir DLLs win automatically, no override needed
elif [ -n "$WINE" ] || [ -x "/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine" ]; then
    CXWINE="${WINE:-/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine}"
    # bottle = the dir named ...Bottles/<name>/drive_c/... in the game path
    BOTTLE_NAME="$(printf '%s' "$GAME" | sed -n 's#.*/Bottles/\([^/]*\)/drive_c/.*#\1#p')"
    if [ -n "$BOTTLE_NAME" ]; then
        if CX_BOTTLE="$BOTTLE_NAME" WINEDEBUG=-all "$CXWINE" reg add \
             "HKCU\\Software\\Wine\\DllOverrides" /v d3d8 /d native,builtin /f \
             >/dev/null 2>&1; then
            echo "bottle '$BOTTLE_NAME': set DLL override d3d8=native,builtin"
        else
            echo "WARNING: could not set d3d8=native,builtin automatically."
            echo "  Add it in CrossOver: bottle '$BOTTLE_NAME' > Wine Configuration"
            echo "  > Libraries > new override for 'd3d8' (native, builtin)."
        fi
        # Borderless-fullscreen only hides the macOS menu bar and suppresses
        # the host cursor (near the Dock) when winemac captures the display,
        # which it does for a fullscreen-sized window while the app is active.
        # This bottle-wide Mac Driver option enables that capture without a
        # display mode switch (mode switches misrender under D3DMetal Retina).
        if CX_BOTTLE="$BOTTLE_NAME" WINEDEBUG=-all "$CXWINE" reg add \
             "HKCU\\Software\\Wine\\Mac Driver" /v CaptureDisplaysForFullscreen \
             /d y /f >/dev/null 2>&1; then
            echo "bottle '$BOTTLE_NAME': set Mac Driver CaptureDisplaysForFullscreen=y"
        else
            echo "WARNING: could not set CaptureDisplaysForFullscreen=y automatically."
            echo "  The menu bar / stray cursor fix needs it. Set it by hand:"
            echo "  CX_BOTTLE='$BOTTLE_NAME' wine reg add 'HKCU\\Software\\Wine\\Mac Driver'"
            echo "    /v CaptureDisplaysForFullscreen /d y /f"
        fi
    fi
fi

echo "installed to $GAME"
echo "  loader:     $GAME/d3d8.dll"
echo "  core:       $GAME/scripts/h2sa_core.asi (widescreen/startup/mouse/fps + profiler overlay)"
echo "  config:     $GAME/scripts/h2sa_core.ini"
echo "  x87 plugin: $GAME/scripts/h2sa_reduced_x87.asi (+ h2sa_reduced_x87/RenderD3D.dll.x87)"
echo "logs after launch: h2sa_asi_loader.log, h2sa_core.log, h2sa_reduced_x87.log"
echo "Launch through Steam so the game's Steam check passes."
